import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { learningCenterService } from '../services/learningCenterService';

export const learningCenterKeys = { all: ['learning-center'] as const, subjects: (institutionId: string, scope = 'all') => ['learning-center', 'subjects', scope, institutionId] as const, student: (institutionId: string, profileId: string) => ['learning-center', 'student', institutionId, profileId] as const, units: (institutionId: string, subjectId: string) => ['learning-center', 'units', institutionId, subjectId] as const, skills: (institutionId: string, unitId: string) => ['learning-center', 'skills', institutionId, unitId] as const, studentActivities: (institutionId: string, profileId: string) => ['learning-center', 'student-activities', institutionId, profileId] as const, teacherActivities: (institutionId: string, teacherId: string) => ['learning-center', 'teacher-activities', institutionId, teacherId] as const, teacherAttempts: (institutionId: string, teacherId: string) => ['learning-center', 'teacher-attempts', institutionId, teacherId] as const, teacherStudents: (institutionId: string) => ['learning-center', 'teacher-students', institutionId] as const, teacherStudentDetail: (institutionId: string, studentId: string) => ['learning-center', 'teacher-student-detail', institutionId, studentId] as const, collections: (institutionId: string, scope: string) => ['learning-center', 'collections', scope, institutionId] as const, progress: (institutionId: string, studentId: string) => ['learning-center', 'progress', institutionId, studentId] as const, guidedSession: (institutionId: string, studentId: string) => ['learning-center', 'guided-session', institutionId, studentId] as const, dailyPlan: (institutionId: string, studentId: string, date: string) => ['learning-center', 'daily-plan', institutionId, studentId, date] as const, gamification: (institutionId: string, studentId: string) => ['learning-center', 'gamification', institutionId, studentId] as const, errorNotebook: (institutionId: string, studentId: string) => ['learning-center', 'error-notebook', institutionId, studentId] as const, errorReview: (errorId: string) => ['learning-center', 'error-review', errorId] as const, questionBank: (institutionId: string) => ['learning-center', 'question-bank', institutionId] as const, simulations: (institutionId: string) => ['learning-center', 'simulations', institutionId] as const, simulationAttempts: (institutionId: string, studentId: string) => ['learning-center', 'simulation-attempts', institutionId, studentId] as const, packages: (institutionId: string, scope = 'all') => ['learning-center', 'packages', scope, institutionId] as const };
export function useLearningSubjects(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.subjects(institutionId ?? ''), queryFn: () => learningCenterService.subjects(institutionId!), enabled: Boolean(institutionId), staleTime: 300000 }); }
export function useStudentLearningSubjects(institutionId?: string, profileId?: string) { return useQuery({ queryKey: learningCenterKeys.subjects(institutionId ?? '', 'student'), queryFn: () => learningCenterService.studentSubjects(institutionId!, profileId!), enabled: Boolean(institutionId && profileId), staleTime: 300000 }); }
export function useLearningStudent(institutionId?: string, profileId?: string) { return useQuery({ queryKey: learningCenterKeys.student(institutionId ?? '', profileId ?? ''), queryFn: () => learningCenterService.studentForProfile(institutionId!, profileId!), enabled: Boolean(institutionId && profileId), staleTime: 300000 }); }
export function useLearningUnits(institutionId?: string, subjectId?: string) { return useQuery({ queryKey: learningCenterKeys.units(institutionId ?? '', subjectId ?? ''), queryFn: () => learningCenterService.units(institutionId!, subjectId!), enabled: Boolean(institutionId && subjectId), staleTime: 300000 }); }
export function useLearningSkills(institutionId?: string, unitId?: string) { return useQuery({ queryKey: learningCenterKeys.skills(institutionId ?? '', unitId ?? ''), queryFn: () => learningCenterService.skills(institutionId!, unitId!), enabled: Boolean(institutionId && unitId), staleTime: 300000 }); }
export function usePublishedLearningActivities(institutionId?: string, profileId?: string) { return useQuery({ queryKey: learningCenterKeys.studentActivities(institutionId ?? '', profileId ?? ''), queryFn: () => learningCenterService.publishedActivities(institutionId!), enabled: Boolean(institutionId && profileId), staleTime: 0, refetchOnMount: 'always', refetchOnWindowFocus: true }); }
export function useTeacherLearningActivities(institutionId?: string, teacherId?: string) { return useQuery({ queryKey: learningCenterKeys.teacherActivities(institutionId ?? '', teacherId ?? ''), queryFn: () => learningCenterService.teacherActivities(institutionId!, teacherId!), enabled: Boolean(institutionId && teacherId), staleTime: 60000 }); }
export function useTeacherLearningClasses(teacherId?: string) { return useQuery({ queryKey: ['learning-center', 'teacher-classes', teacherId ?? ''] as const, queryFn: () => learningCenterService.teacherClasses(teacherId!), enabled: Boolean(teacherId), staleTime: 300000 }); }
export function useTeacherLearningAttempts(institutionId?: string, teacherId?: string) { return useQuery({ queryKey: learningCenterKeys.teacherAttempts(institutionId ?? '', teacherId ?? ''), queryFn: () => learningCenterService.teacherAttempts(institutionId!, teacherId!), enabled: Boolean(institutionId && teacherId), staleTime: 60000 }); }
export function useTeacherLearningStudents(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.teacherStudents(institutionId ?? ''), queryFn: () => learningCenterService.teacherStudents(institutionId!), enabled: Boolean(institutionId), staleTime: 30000, retry: false }); }
export function useTeacherLearningStudentDetail(institutionId?: string, studentId?: string) { return useQuery({ queryKey: learningCenterKeys.teacherStudentDetail(institutionId ?? '', studentId ?? ''), queryFn: () => learningCenterService.teacherStudentDetail(institutionId!, studentId!), enabled: Boolean(institutionId && studentId), staleTime: 30000, retry: false }); }
export function useStudentLearningCollections(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.collections(institutionId ?? '', 'student'), queryFn: () => learningCenterService.studentCollections(institutionId!), enabled: Boolean(institutionId), staleTime: 60000 }); }
export function useTeacherLearningCollections(institutionId?: string, teacherId?: string) { return useQuery({ queryKey: learningCenterKeys.collections(institutionId ?? '', `teacher:${teacherId ?? ''}`), queryFn: () => learningCenterService.teacherCollections(institutionId!, teacherId!), enabled: Boolean(institutionId && teacherId), staleTime: 60000 }); }
export function useLearningProgress(institutionId?: string, studentId?: string) { return useQuery({ queryKey: learningCenterKeys.progress(institutionId ?? '', studentId ?? ''), queryFn: () => learningCenterService.progress(institutionId!, studentId!), enabled: Boolean(institutionId && studentId), staleTime: 60000 }); }
export function useGuidedLearningSession(institutionId?: string, studentId?: string) { return useQuery({ queryKey: learningCenterKeys.guidedSession(institutionId ?? '', studentId ?? ''), queryFn: async () => { try { return await learningCenterService.guidedSession(institutionId!, studentId!); } catch { return null; } }, enabled: Boolean(institutionId && studentId), staleTime: 30000, retry: false }); }
export function useLearningDailyPlan(institutionId?: string, studentId?: string) { const date = new Date().toISOString().slice(0, 10); return useQuery({ queryKey: learningCenterKeys.dailyPlan(institutionId ?? '', studentId ?? '', date), queryFn: async () => { try { return await learningCenterService.dailyPlan(institutionId!, studentId!, date); } catch { return null; } }, enabled: Boolean(institutionId && studentId), staleTime: 30000, retry: false }); }
export function useLearningGamification(institutionId?: string, studentId?: string) { return useQuery({ queryKey: learningCenterKeys.gamification(institutionId ?? '', studentId ?? ''), queryFn: async () => { try { return await learningCenterService.gamification(institutionId!, studentId!); } catch { return null; } }, enabled: Boolean(institutionId && studentId), staleTime: 30000, retry: false }); }
export function useLearningErrorNotebook(institutionId?: string, studentId?: string) { return useQuery({ queryKey: learningCenterKeys.errorNotebook(institutionId ?? '', studentId ?? ''), queryFn: async () => { try { return await learningCenterService.errorNotebook(institutionId!, studentId!); } catch { return []; } }, enabled: Boolean(institutionId && studentId), staleTime: 30000, retry: false }); }
export function useLearningErrorReview(errorId?: string) { return useQuery({ queryKey: learningCenterKeys.errorReview(errorId ?? ''), queryFn: () => learningCenterService.errorReview(errorId!), enabled: Boolean(errorId), staleTime: 0, retry: false }); }
export function useSubmitLearningErrorReview(institutionId?: string, studentId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ errorId, answer }: { errorId: string; answer: unknown }) => learningCenterService.submitErrorReview(errorId, answer), onSuccess: () => { if (institutionId && studentId) { void client.invalidateQueries({ queryKey: learningCenterKeys.errorNotebook(institutionId, studentId) }); void client.invalidateQueries({ queryKey: learningCenterKeys.progress(institutionId, studentId) }); void client.invalidateQueries({ queryKey: learningCenterKeys.gamification(institutionId, studentId) }); } } }); }
export function useTeacherQuestionBank(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.questionBank(institutionId ?? ''), queryFn: async () => { try { return await learningCenterService.questionBank(institutionId!); } catch { return []; } }, enabled: Boolean(institutionId), staleTime: 60000, retry: false }); }
export function useLearningSimulations(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.simulations(institutionId ?? ''), queryFn: async () => { try { return await learningCenterService.simulations(institutionId!); } catch { return []; } }, enabled: Boolean(institutionId), staleTime: 60000, retry: false }); }
export function useLearningSimulationAttempts(institutionId?: string, studentId?: string) { return useQuery({ queryKey: learningCenterKeys.simulationAttempts(institutionId ?? '', studentId ?? ''), queryFn: async () => { try { return await learningCenterService.simulationAttempts(institutionId!, studentId!); } catch { return []; } }, enabled: Boolean(institutionId && studentId), staleTime: 30000, retry: false }); }
export function useLearningPackages(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.packages(institutionId ?? ''), queryFn: async () => { try { return await learningCenterService.packages(institutionId!); } catch { return []; } }, enabled: Boolean(institutionId), staleTime: 60000, retry: false }); }
export function useStudentLearningPackages(institutionId?: string, studentId?: string) { return useQuery({ queryKey: learningCenterKeys.packages(institutionId ?? '', `student:${studentId ?? ''}`), queryFn: async () => { try { return await learningCenterService.studentPackages(institutionId!, studentId!); } catch { return []; } }, enabled: Boolean(institutionId && studentId), staleTime: 30000, retry: false }); }
export function useAssignLearningPackage(institutionId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: (input: { packageId: string; classId?: string; studentId?: string; dueAt?: string }) => learningCenterService.assignPackage({ institutionId: institutionId!, ...input }), onSuccess: () => { if (institutionId) void client.invalidateQueries({ queryKey: learningCenterKeys.packages(institutionId) }); } }); }
export function useStartLearningSimulation(institutionId?: string, studentId?: string) { return useMutation({ mutationFn: (simulationId: string) => learningCenterService.startSimulation({ institutionId: institutionId!, studentId: studentId!, simulationId }) }); }
export function useSubmitLearningSimulation(institutionId?: string, studentId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ attemptId, answers, durationSeconds }: { attemptId: string; answers: Array<{ question_bank_id: string; answer: unknown }>; durationSeconds: number }) => learningCenterService.submitSimulation(attemptId, answers, durationSeconds), onSuccess: () => { if (institutionId && studentId) { void client.invalidateQueries({ queryKey: learningCenterKeys.progress(institutionId, studentId) }); void client.invalidateQueries({ queryKey: learningCenterKeys.gamification(institutionId, studentId) }); } } }); }
export function useStartGuidedLearningSession(institutionId?: string, studentId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: (targetCanonicalSkillId: string) => learningCenterService.startGuidedSession({ institutionId: institutionId!, studentId: studentId!, targetCanonicalSkillId }), onSuccess: () => { if (institutionId && studentId) { void client.invalidateQueries({ queryKey: learningCenterKeys.guidedSession(institutionId, studentId) }); void client.invalidateQueries({ queryKey: learningCenterKeys.dailyPlan(institutionId, studentId, new Date().toISOString().slice(0, 10)) }); } } }); }
export function useCompleteGuidedLearningStep(institutionId?: string, studentId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ stepId, status, metadata }: { stepId: string; status?: 'COMPLETED' | 'SKIPPED'; metadata?: Record<string, unknown> }) => learningCenterService.completeGuidedStep(stepId, status, metadata), onSuccess: () => { if (institutionId && studentId) { void client.invalidateQueries({ queryKey: learningCenterKeys.guidedSession(institutionId, studentId) }); void client.invalidateQueries({ queryKey: learningCenterKeys.dailyPlan(institutionId, studentId, new Date().toISOString().slice(0, 10)) }); void client.invalidateQueries({ queryKey: learningCenterKeys.gamification(institutionId, studentId) }); } } }); }
export function useSubmitLearningAttempt(institutionId?: string, studentId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ activityId, answers }: { activityId: string; answers: Array<{ question_id: string; answer: unknown }> }) => learningCenterService.submitAttempt(activityId, answers), onSuccess: () => { if (institutionId && studentId) void client.invalidateQueries({ queryKey: learningCenterKeys.progress(institutionId, studentId) }); } }); }
export function useSubmitLearningAttemptWithFeedback(institutionId?: string, studentId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ activityId, answers }: { activityId: string; answers: Array<{ question_id: string; answer: unknown }> }) => learningCenterService.submitAttemptWithFeedback(activityId, answers), onSuccess: () => { if (institutionId && studentId) { void client.invalidateQueries({ queryKey: learningCenterKeys.progress(institutionId, studentId) }); void client.invalidateQueries({ queryKey: learningCenterKeys.gamification(institutionId, studentId) }); void client.invalidateQueries({ queryKey: learningCenterKeys.errorNotebook(institutionId, studentId) }); } } }); }
