import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { learningCenterService } from '../services/learningCenterService';

export const learningCenterKeys = { all: ['learning-center'] as const, subjects: (institutionId: string, scope = 'all') => ['learning-center', 'subjects', scope, institutionId] as const, student: (institutionId: string, profileId: string) => ['learning-center', 'student', institutionId, profileId] as const, units: (institutionId: string, subjectId: string) => ['learning-center', 'units', institutionId, subjectId] as const, skills: (institutionId: string, unitId: string) => ['learning-center', 'skills', institutionId, unitId] as const, activities: (institutionId: string) => ['learning-center', 'activities', institutionId] as const, teacherActivities: (institutionId: string, teacherId: string) => ['learning-center', 'teacher-activities', institutionId, teacherId] as const, teacherAttempts: (institutionId: string, teacherId: string) => ['learning-center', 'teacher-attempts', institutionId, teacherId] as const, collections: (institutionId: string, scope: string) => ['learning-center', 'collections', scope, institutionId] as const, progress: (institutionId: string, studentId: string) => ['learning-center', 'progress', institutionId, studentId] as const };
export function useLearningSubjects(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.subjects(institutionId ?? ''), queryFn: () => learningCenterService.subjects(institutionId!), enabled: Boolean(institutionId), staleTime: 300000 }); }
export function useStudentLearningSubjects(institutionId?: string, profileId?: string) { return useQuery({ queryKey: learningCenterKeys.subjects(institutionId ?? '', 'student'), queryFn: () => learningCenterService.studentSubjects(institutionId!, profileId!), enabled: Boolean(institutionId && profileId), staleTime: 300000 }); }
export function useLearningStudent(institutionId?: string, profileId?: string) { return useQuery({ queryKey: learningCenterKeys.student(institutionId ?? '', profileId ?? ''), queryFn: () => learningCenterService.studentForProfile(institutionId!, profileId!), enabled: Boolean(institutionId && profileId), staleTime: 300000 }); }
export function useLearningUnits(institutionId?: string, subjectId?: string) { return useQuery({ queryKey: learningCenterKeys.units(institutionId ?? '', subjectId ?? ''), queryFn: () => learningCenterService.units(institutionId!, subjectId!), enabled: Boolean(institutionId && subjectId), staleTime: 300000 }); }
export function useLearningSkills(institutionId?: string, unitId?: string) { return useQuery({ queryKey: learningCenterKeys.skills(institutionId ?? '', unitId ?? ''), queryFn: () => learningCenterService.skills(institutionId!, unitId!), enabled: Boolean(institutionId && unitId), staleTime: 300000 }); }
export function usePublishedLearningActivities(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.activities(institutionId ?? ''), queryFn: () => learningCenterService.publishedActivities(institutionId!), enabled: Boolean(institutionId), staleTime: 60000 }); }
export function useTeacherLearningActivities(institutionId?: string, teacherId?: string) { return useQuery({ queryKey: learningCenterKeys.teacherActivities(institutionId ?? '', teacherId ?? ''), queryFn: () => learningCenterService.teacherActivities(institutionId!, teacherId!), enabled: Boolean(institutionId && teacherId), staleTime: 60000 }); }
export function useTeacherLearningAttempts(institutionId?: string, teacherId?: string) { return useQuery({ queryKey: learningCenterKeys.teacherAttempts(institutionId ?? '', teacherId ?? ''), queryFn: () => learningCenterService.teacherAttempts(institutionId!, teacherId!), enabled: Boolean(institutionId && teacherId), staleTime: 60000 }); }
export function useStudentLearningCollections(institutionId?: string) { return useQuery({ queryKey: learningCenterKeys.collections(institutionId ?? '', 'student'), queryFn: () => learningCenterService.studentCollections(institutionId!), enabled: Boolean(institutionId), staleTime: 60000 }); }
export function useTeacherLearningCollections(institutionId?: string, teacherId?: string) { return useQuery({ queryKey: learningCenterKeys.collections(institutionId ?? '', `teacher:${teacherId ?? ''}`), queryFn: () => learningCenterService.teacherCollections(institutionId!, teacherId!), enabled: Boolean(institutionId && teacherId), staleTime: 60000 }); }
export function useLearningProgress(institutionId?: string, studentId?: string) { return useQuery({ queryKey: learningCenterKeys.progress(institutionId ?? '', studentId ?? ''), queryFn: () => learningCenterService.progress(institutionId!, studentId!), enabled: Boolean(institutionId && studentId), staleTime: 60000 }); }
export function useSubmitLearningAttempt(institutionId?: string, studentId?: string) { const client = useQueryClient(); return useMutation({ mutationFn: ({ activityId, answers }: { activityId: string; answers: Array<{ question_id: string; answer: unknown }> }) => learningCenterService.submitAttempt(activityId, answers), onSuccess: () => { if (institutionId && studentId) void client.invalidateQueries({ queryKey: learningCenterKeys.progress(institutionId, studentId) }); } }); }
