import { useEffect, useMemo, useState } from 'react';
import { Bot, Send, Volume2, VolumeX, X } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { getAssistantFeatures, recordAssistantUsage, type AssistantFeature } from '../services/featureRegistry';
import type { UserRole } from '../types';

const normalize = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

export default function AssistantTec({ role, institutionId }: { role: UserRole; institutionId: string | null }) {
  const navigate = useNavigate();
  const location = useLocation();
  const [open, setOpen] = useState(false);
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('Olá! O que você deseja fazer?');
  const [selected, setSelected] = useState<AssistantFeature | null>(null);
  const [voiceEnabled, setVoiceEnabled] = useState(false);
  const features = getAssistantFeatures(role);
  const results = useMemo(() => { const terms = normalize(question).trim().split(/\s+/).filter(Boolean); if (!terms.length) return []; return features.map((item) => { const haystack = normalize(`${item.label} ${item.description} ${item.id} ${item.keywords.join(' ')}`); const score = terms.reduce((total, term) => total + (haystack.includes(term) ? 1 : 0), 0); return { item, score }; }).filter(({ score }) => score > 0).sort((a, b) => b.score - a.score).map(({ item }) => item); }, [features, question]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  function speak(text: string): void { if (!voiceEnabled || typeof window === 'undefined' || !('speechSynthesis' in window)) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'pt-BR'; utterance.rate = 1; window.speechSynthesis.speak(utterance); }
  function go(item: AssistantFeature): void { recordAssistantUsage(item.id, institutionId); setSelected(item); const text = `Encontrei ${item.label}. Vou abrir essa tela para você.`; setAnswer(text); speak(text); navigate(item.route); setQuestion(''); }
  function ask(): void { const best = results[0]; if (!question.trim()) return; if (best) { go(best); return; } const text = 'Ainda não encontrei essa área para o seu perfil. Tente escrever o nome da tela ou do recurso.'; setAnswer(text); speak(text); }
  return <><button type="button" onClick={() => setOpen(true)} aria-label="Abrir Assistente TEC" className="fixed bottom-5 right-5 z-40 inline-flex h-12 w-12 items-center justify-center rounded-full bg-[#005bbf] text-white shadow-lg hover:bg-[#004a9c]" title="Assistente TEC"><Bot className="h-5 w-5" /></button>{open && <div className="fixed bottom-20 right-5 z-50 w-[min(420px,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#005bbf] px-4 py-3 text-white"><div><strong>✦ Assistente TEC</strong><p className="text-xs text-blue-100">Converse com o TEC para encontrar qualquer recurso</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Fechar assistente"><X className="h-5 w-5" /></button></header><div className="space-y-4 p-4"><div className="flex items-start gap-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-900"><Bot className="mt-0.5 h-5 w-5 shrink-0" /><span>{answer}</span></div><form onSubmit={(event) => { event.preventDefault(); ask(); }} className="flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 focus-within:border-[#005bbf]"><input autoFocus value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Digite o que você quer fazer..." aria-label="Pergunte ao Assistente TEC" className="min-w-0 flex-1 text-sm outline-none" /><button type="submit" aria-label="Enviar pergunta" className="text-[#005bbf]" title="Enviar"><Send className="h-4 w-4" /></button></form><div className="flex items-center justify-between"><span className="text-xs text-slate-400">Ex.: “abrir alunos”, “ver financeiro” ou “personalizar login”</span><button type="button" onClick={() => setVoiceEnabled((value) => !value)} aria-label={voiceEnabled ? 'Desativar áudio' : 'Ativar áudio'} title={voiceEnabled ? 'Desativar áudio' : 'Ativar áudio'} className="inline-flex items-center gap-1 text-xs font-semibold text-slate-600">{voiceEnabled ? <Volume2 className="h-4 w-4 text-[#005bbf]" /> : <VolumeX className="h-4 w-4" />} Áudio</button></div>{question.trim() && <div className="space-y-2">{results.slice(0, 3).map((item) => <button key={item.id} type="button" onClick={() => go(item)} className="flex w-full items-center justify-between rounded-lg border border-slate-200 p-3 text-left hover:border-[#005bbf] hover:bg-blue-50"><span><strong className="block text-sm text-slate-800">{item.label}</strong><span className="text-xs text-slate-500">{item.description}</span></span><Send className="h-4 w-4 text-[#005bbf]" /></button>)}{results.length === 0 && <p className="text-sm text-slate-500">Não encontrei um recurso correspondente.</p>}</div>}{selected && <p className="text-right text-[11px] text-slate-400">Aberto agora: {selected.label} · {location.pathname}</p>}</div></div>}</>;
}
