import { useEffect, useMemo, useState } from 'react';
import { Bot, ChevronRight, Command, MapPin, X } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { getAssistantFeatures, recordAssistantUsage, type AssistantFeature } from '../services/featureRegistry';
import type { UserRole } from '../types';

export default function AssistantTec({ role, institutionId }: { role: UserRole; institutionId: string | null }) {
  const navigate = useNavigate();
  const location = useLocation();
  const [open, setOpen] = useState(false);
  const [question, setQuestion] = useState('');
  const [selected, setSelected] = useState<AssistantFeature | null>(null);
  const features = getAssistantFeatures(role);
  const results = useMemo(() => { const term = question.trim().toLowerCase(); return term ? features.filter((item) => `${item.label} ${item.description} ${item.id}`.toLowerCase().includes(term)) : features; }, [features, question]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.shiftKey && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(true); } if (event.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  function go(item: AssistantFeature, show: boolean) { recordAssistantUsage(item.id, institutionId); setSelected(item); navigate(item.route); if (show) window.setTimeout(() => { const link = Array.from(document.querySelectorAll<HTMLAnchorElement>('a[href]')).find((element) => element.getAttribute('href')?.includes(item.route.split('?')[1] ?? item.route)); link?.scrollIntoView({ behavior: 'smooth', block: 'center' }); link?.classList.add('assistant-focus'); window.setTimeout(() => link?.classList.remove('assistant-focus'), 3500); }, 250); }
  return <><button type="button" onClick={() => setOpen(true)} aria-label="Abrir Assistente TEC" className="fixed bottom-5 right-5 z-40 inline-flex h-12 w-12 items-center justify-center rounded-full bg-[#005bbf] text-white shadow-lg hover:bg-[#004a9c]" title="Assistente TEC (Ctrl + K)"><Bot className="h-5 w-5" /></button>{open && <div className="fixed bottom-20 right-5 z-50 w-[min(420px,calc(100vw-2rem))] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#005bbf] px-4 py-3 text-white"><div><strong>✦ Assistente TEC</strong><p className="text-xs text-blue-100">Navegação inteligente · Ctrl + K</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Fechar assistente"><X className="h-5 w-5" /></button></header><div className="space-y-4 p-4"><label className="flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2"><Command className="h-4 w-4 text-slate-400" /><input autoFocus value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="O que você quer fazer?" className="min-w-0 flex-1 text-sm outline-none" /></label><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Sugestões</p><div className="space-y-2">{results.map((item) => <div key={item.id} className="rounded-lg border border-slate-200 p-3"><button type="button" onClick={() => go(item, false)} className="flex w-full items-center justify-between text-left text-sm font-semibold text-slate-700"><span>{item.label}</span><ChevronRight className="h-4 w-4" /></button><div className="mt-2 flex gap-2"><button type="button" onClick={() => go(item, false)} className="rounded-md bg-[#005bbf] px-2.5 py-1.5 text-xs font-bold text-white">Abrir tela</button><button type="button" onClick={() => go(item, true)} className="inline-flex items-center gap-1 rounded-md border border-slate-300 px-2.5 py-1.5 text-xs font-semibold text-slate-600"><MapPin className="h-3 w-3" /> Mostrar onde fica</button></div></div>)}</div>{selected && <p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-900">{selected.description}</p>}{results.length === 0 && <p className="text-sm text-slate-500">Nenhum recurso disponível para este perfil.</p>}<p className="text-right text-[11px] text-slate-400">Tela atual: {location.pathname}</p></div></div>}</>;
}
