import { useMemo, useState } from 'react';
import { CircleDollarSign, ReceiptText, Search, Wallet } from 'lucide-react';
import { useAuth } from '../../../contexts/AuthContext';
import { useCurrentInstitution } from '../../../hooks/useCurrentInstitution';
import { useFinance } from '../../../hooks/useFinance';

const money = (cents: number) => (cents / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const statusLabel: Record<string, string> = { OPEN: 'Em aberto', OVERDUE: 'Em atraso', PAID: 'Pago', CANCELLED: 'Cancelado', PARTIALLY_PAID: 'Parcial', DRAFT: 'Rascunho', NEGOTIATED: 'Negociado' };

export default function FinanceTab() {
  const { profile } = useAuth();
  const institution = useCurrentInstitution(profile?.id);
  const finance = useFinance(institution.data ?? '');
  const [search, setSearch] = useState('');
  const invoices = useMemo(() => (finance.invoices.data ?? []).filter((invoice) => `${invoice.reference} ${invoice.student?.profiles?.full_name ?? ''} ${invoice.responsible?.full_name ?? ''}`.toLowerCase().includes(search.toLowerCase())), [finance.invoices.data, search]);
  const summary = finance.summary.data;
  if (finance.invoices.isLoading) return <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">Carregando financeiro...</div>;
  if (finance.invoices.error) return <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">Não foi possível carregar o Financeiro. Verifique se a estrutura financeira foi aplicada neste ambiente.</div>;
  return <div className="space-y-6">
    <header><div className="flex items-center gap-3"><Wallet className="h-6 w-6 text-blue-700" /><h1 className="text-2xl font-bold text-slate-900 dark:text-white">Financeiro</h1></div><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Contratos, faturas e recebimentos da instituição.</p></header>
    <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800 dark:border-amber-900/70 dark:bg-amber-950/30 dark:text-amber-200">Ambiente de simulação. Nenhum pagamento real será processado.</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Recebido no mês', summary?.received ?? 0, Wallet], ['A receber', summary?.receivable ?? 0, ReceiptText], ['Em atraso', summary?.overdue ?? 0, CircleDollarSign], ['Inadimplência', `${Math.round((summary?.delinquency ?? 0) * 100)}%`, CircleDollarSign]].map(([label, value, Icon]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between"><span className="text-sm text-slate-600 dark:text-slate-300">{label}</span><Icon className="h-5 w-5 text-blue-700" /></div><strong className="mt-3 block text-2xl text-slate-900 dark:text-white">{typeof value === 'number' ? money(value) : value}</strong></div>)}</div>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4 dark:border-slate-700"><h2 className="font-bold text-slate-900 dark:text-white">Faturas</h2><label className="flex min-w-[220px] items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 dark:border-slate-600"><Search className="h-4 w-4 text-slate-400" /><input aria-label="Buscar faturas" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Aluno ou referência" className="min-w-0 bg-transparent text-sm outline-none dark:text-white" /></label></div>{invoices.length === 0 ? <p className="p-8 text-center text-sm text-slate-500">Nenhuma fatura encontrada.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th className="p-4">Aluno</th><th className="p-4">Responsável financeiro</th><th className="p-4">Referência</th><th className="p-4">Vencimento</th><th className="p-4">Valor</th><th className="p-4">Status</th><th className="p-4">Ações</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-t border-slate-200 dark:border-slate-700"><td className="p-4 font-semibold text-slate-900 dark:text-white">{invoice.student?.profiles?.full_name ?? 'Aluno'}</td><td className="p-4 text-slate-600 dark:text-slate-300">{invoice.responsible?.full_name ?? 'Não informado'}</td><td className="p-4">{invoice.reference}</td><td className="p-4">{new Date(`${invoice.due_date}T00:00:00`).toLocaleDateString('pt-BR')}</td><td className="p-4">{money(Number(invoice.amount_due))}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold dark:bg-slate-700">{statusLabel[invoice.status] ?? invoice.status}</span></td><td className="p-4">{invoice.status !== 'PAID' && <button type="button" onClick={() => finance.payment.mutate({ invoiceId: invoice.id, amount: Number(invoice.amount_due) })} disabled={finance.payment.isPending} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-60">Simular pagamento</button>}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
