import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useInstitution } from '../../contexts/InstitutionContext';
import { useTeacherQuestionBank } from '../../hooks/useLearningCenter';
import { PedagogicalCenterHeader, PageState } from './PedagogicalCenterNav';

export default function PedagogicalCenterContentPage() {
  const { currentInstitutionId } = useInstitution();
  const bank = useTeacherQuestionBank(currentInstitutionId ?? undefined);
  const [search, setSearch] = useState('');
  const [source, setSource] = useState('ALL');
  const [year, setYear] = useState('ALL');
  const [area, setArea] = useState('ALL');
  const years = useMemo(() => [...new Set((bank.data ?? []).map((item) => item.source_year).filter((value): value is number => Boolean(value)))].sort((left, right) => right - left), [bank.data]);
  const areas = useMemo(() => [...new Set((bank.data ?? []).map((item) => item.subject_area).filter(Boolean))].sort(), [bank.data]);
  const filtered = useMemo(() => { const query = search.trim().toLocaleLowerCase('pt-BR'); return (bank.data ?? []).filter((item) => (!query || `${item.statement} ${item.subject_area} ${item.topic ?? ''} ${item.source_name ?? ''}`.toLocaleLowerCase('pt-BR').includes(query)) && (source === 'ALL' || (source === 'ENEM' ? item.package_type === 'ENEM' : item.package_type !== 'ENEM')) && (year === 'ALL' || String(item.source_year) === year) && (area === 'ALL' || item.subject_area === area)); }, [area, bank.data, search, source, year]);
  return <div className="space-y-6"><PedagogicalCenterHeader subtitle="Encontre conteúdo e adicione questões a uma atividade contextualizada." /><section className="rounded-xl border bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold dark:text-white">Banco de questões</h2><p className="mt-1 text-sm text-slate-500">Filtre por ano, área e origem antes de montar uma atividade.</p></div><Link to="/teacher/pedagogical-center/activities/new" className="rounded-lg bg-[#005bbf] px-3 py-2 text-xs font-bold text-white">Nova atividade</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="Buscar conteúdo" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar enunciado ou assunto" className="rounded-lg border px-3 py-2 text-sm dark:bg-slate-900 dark:text-white" /><select aria-label="Filtrar origem" value={source} onChange={(event) => setSource(event.target.value)} className="rounded-lg border px-3 py-2 text-sm dark:bg-slate-900 dark:text-white"><option value="ALL">Todas as origens</option><option value="ENEM">ENEM oficial</option><option value="OTHER">TecEscola e professor</option></select><select aria-label="Filtrar ano" value={year} onChange={(event) => setYear(event.target.value)} className="rounded-lg border px-3 py-2 text-sm dark:bg-slate-900 dark:text-white"><option value="ALL">Todos os anos</option>{years.map((item) => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Filtrar área" value={area} onChange={(event) => setArea(event.target.value)} className="rounded-lg border px-3 py-2 text-sm dark:bg-slate-900 dark:text-white"><option value="ALL">Todas as áreas</option>{areas.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>{bank.isLoading ? <PageState>Carregando conteúdo...</PageState> : bank.isError ? <PageState error>Não foi possível carregar o banco de questões.</PageState> : filtered.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{filtered.slice(0, 24).map((item) => <article key={item.id} className="rounded-lg border p-4 dark:border-slate-700"><p className="line-clamp-3 text-sm font-semibold dark:text-white">{item.statement}</p><p className="mt-2 text-xs text-slate-500">{item.subject_area}{item.topic ? ` · ${item.topic}` : ''}{item.source_year ? ` · ${item.source_year}` : ''} · {item.package_type}</p><Link to={`/teacher/pedagogical-center/activities/new?questionBankId=${item.id}`} className="mt-3 inline-flex text-xs font-bold text-[#005bbf]">Adicionar à atividade</Link></article>)}</div> : <PageState>Nenhum conteúdo corresponde aos filtros.</PageState>}</section></div>;
}
