import { CheckCircle2, ChevronLeft, GraduationCap, Send } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { usePublishedLearningActivities, useSubmitLearningAttempt } from '../../hooks/useLearningCenter';
import { useInstitution } from '../../contexts/InstitutionContext';
import { useAuth } from '../../contexts/AuthContext';

export default function PracticePage() {
  const { activityId } = useParams(); const navigate = useNavigate(); const { profile } = useAuth(); const { currentInstitutionId } = useInstitution();
  const query = usePublishedLearningActivities(currentInstitutionId ?? undefined, profile?.id); const activity = query.data?.find((item) => item.id === activityId); const questions = useMemo(() => [...(activity?.learning_questions ?? [])].sort((a, b) => a.sort_order - b.sort_order), [activity]);
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [result, setResult] = useState<{ score: number; total_points: number; mastery_percent: number } | null>(null); const submit = useSubmitLearningAttempt(currentInstitutionId ?? undefined, profile?.id);
  if (query.isLoading) return <div className="grid min-h-48 place-items-center text-sm text-slate-500">Carregando prática...</div>;
  if (!activity) return <div className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">Esta atividade não está disponível para você.</div>;
  const send = () => { void submit.mutateAsync({ activityId: activity.id, answers: questions.map((question) => ({ question_id: question.id, answer: answers[question.id] ?? '' })) }).then((value) => setResult(value[0] ?? value as unknown as { score: number; total_points: number; mastery_percent: number })); };
  if (result) return <section className="mx-auto max-w-xl rounded-xl border border-emerald-200 bg-white p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-500"/><h1 className="mt-4 text-2xl font-bold">Prática concluída</h1><p className="mt-2 text-slate-500">Você acertou {result.score} de {result.total_points} pontos.</p><p className="mt-4 text-sm font-semibold text-[#005bbf]">Domínio atualizado: {result.mastery_percent}%</p><Link to="/student/study" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#005bbf] px-4 py-2 text-sm font-bold text-white">Voltar à Central de Estudos</Link></section>;
  return <div className="mx-auto max-w-3xl space-y-6"><Link to="/student/study" className="inline-flex items-center gap-2 text-sm font-semibold text-[#005bbf]"><ChevronLeft className="h-4 w-4"/>Central de Estudos</Link><header><div className="flex items-center gap-3"><GraduationCap className="h-7 w-7 text-[#005bbf]"/><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#005bbf]">Prática</p><h1 className="text-2xl font-bold dark:text-white">{activity.title}</h1></div></div><p className="mt-2 text-sm text-slate-500">{activity.description ?? 'Responda às questões e acompanhe seu progresso.'}</p></header><div className="space-y-4">{questions.map((question, index) => <fieldset key={question.id} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"><legend className="text-sm font-bold dark:text-white">Questão {index + 1} de {questions.length}</legend><p className="mt-3 text-sm dark:text-slate-200">{question.question_text}</p><div className="mt-4 space-y-2">{(question.options_json.length ? question.options_json : ['Verdadeiro', 'Falso']).map((option) => <label key={option} className="flex cursor-pointer items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm hover:border-[#005bbf] dark:border-slate-700 dark:text-slate-200"><input type="radio" name={question.id} value={option} checked={answers[question.id] === option} onChange={() => setAnswers((current) => ({ ...current, [question.id]: option }))}/>{option}</label>)}</div></fieldset>)}</div><button type="button" onClick={send} disabled={submit.isPending || questions.some((question) => !answers[question.id])} className="inline-flex items-center gap-2 rounded-lg bg-[#005bbf] px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><Send className="h-4 w-4"/>{submit.isPending ? 'Enviando...' : 'Finalizar prática'}</button>{submit.isError && <p role="alert" className="text-sm text-red-600">{submit.error.message}</p>}</div>;
}
